ShorterApp/config/routes.rb
Rails.application.routes.draw do
  resources :urls, :only => [:new, :create]
  root to: 'urls#new'

end

ShorterApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

ShorterApp/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
  end

  def create
     if !params[:url].blank?
      client = Bitly.client
        @url = client.shorten(params[:url])
	@urls = @url.short_url
	#@urls = client.shorten(params[:url])
      #@u = client.clicks(params[@urls.short_url])
	@u = Bitly.client.clicks(@url.short_url).global_clicks
	#@u = Bitly.client.shorten('http://www.google.com').clicks
     end
  end

end

ShorterApp/app/helpers/application_helper.rb
module ApplicationHelper
end

ShorterApp/app/helpers/urls_helper.rb
module UrlsHelper
end

ShorterApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShorterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ShorterApp/app/views/urls/create.html.erb
stats info : <%= @u %> <br/>
stats info2 : <%= @urls %>
<%= link_to "Create another Url", root_path %>

ShorterApp/app/views/urls/new.html.erb
<h1>Create a new Bit.ly URL:</h1>

<%= form_for "", url: urls_path, method: :post do |f| %>
 <%= f.label :url %>
 <%= f.text_field :url %>
 <%= f.submit "Create Url" %>
<% end %>