my APPS/BookApp/config/routes.rb
Rails.application.routes.draw do
  resources :books

end

my APPS/BookApp/app/models/book.rb
class Book < ActiveRecord::Base

def self.search(query)
 where("book like ?", "%#{query}%") 
end
 
end

my APPS/BookApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

my APPS/BookApp/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
   if params[:search]
    @books = Book.search(params[:search])
   else
    @books = Book.all
   end
   respond_to do |format|
      format.js
      format.html # index.html.erb
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book)
    end
end

my APPS/BookApp/app/helpers/application_helper.rb
module ApplicationHelper
end

my APPS/BookApp/app/helpers/books_helper.rb
module BooksHelper
end

my APPS/BookApp/app/views/books/_books.html.erb
<table>
  <thead>
    <tr>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

my APPS/BookApp/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :book %><br>
    <%= f.text_field :book %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my APPS/BookApp/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

my APPS/BookApp/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<%= form_tag books_path, :method => 'get', id: "books_search", remote: true  do %>
  <%= text_field_tag :search, params[:search] %>
  <div class="action"><%= submit_tag "search", :name => nil %></div>
<% end %>


<div id="books"><%= render 'books' %></div>


<br>

<%= link_to 'New Book', new_book_path, id: "new_link", remote: true  %>

my APPS/BookApp/app/views/books/index.js.erb
$('#books').html('<%= j render("books") %>')

my APPS/BookApp/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

my APPS/BookApp/app/views/books/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

my APPS/BookApp/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book.book %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>